apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neuvector
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: neuvector
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: core
    repoURL: https://neuvector.github.io/neuvector-helm
    targetRevision: 2.2.2
    helm:
      releaseName: neuvector
      values: |
        controller:
          replicas: 1
        cve:
          scanner:
            replicas: 1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
