apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyverno-signed
  namespace: sigstore-enforced
  annotations:
    deploymentTag: unsigned
spec:
  selector:
    matchLabels:
      app: kyverno-signed
  template:
    metadata:
      labels:
        app: kyverno-signed
    spec:
      containers:
      - name: test-verify-image
        image: ghcr.io/kyverno/test-verify-image:unsigned
